package com.github.aliakseikaraliou.shoplist.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.github.aliakseikaraliou.shoplist.db.Product;
import com.github.aliakseikaraliou.shoplist.db.ProductList;

import com.github.aliakseikaraliou.shoplist.db.ProductDao;
import com.github.aliakseikaraliou.shoplist.db.ProductListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productDaoConfig;
    private final DaoConfig productListDaoConfig;

    private final ProductDao productDao;
    private final ProductListDao productListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        productListDaoConfig = daoConfigMap.get(ProductListDao.class).clone();
        productListDaoConfig.initIdentityScope(type);

        productDao = new ProductDao(productDaoConfig, this);
        productListDao = new ProductListDao(productListDaoConfig, this);

        registerDao(Product.class, productDao);
        registerDao(ProductList.class, productListDao);
    }
    
    public void clear() {
        productDaoConfig.clearIdentityScope();
        productListDaoConfig.clearIdentityScope();
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public ProductListDao getProductListDao() {
        return productListDao;
    }

}
