package com.github.aliakseikaraliou.shoplist.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRODUCT_LIST".
 */
@Entity
public class ProductList {

    @Id
    private Long id;
    private String Name;

    @Generated
    public ProductList() {
    }

    public ProductList(Long id) {
        this.id = id;
    }

    @Generated
    public ProductList(Long id, String Name) {
        this.id = id;
        this.Name = Name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

}
